spring.application.name=nagahoribashi_walk

# Postgresのドライバー設定
spring.datasource.driver-class-name=org.postgresql.Driver
# データベースへの接続URLを設定
spring.datasource.url=jdbc:postgresql://localhost:5432/nagahoribashi_walkdb

# データベース接続の為のユーザー名
spring.datasource.username=nagahoribashi_walk
# データベース接続の為のパスワード
spring.datasource.password=nagahoribashi

# SQLスクリプトの初期化モードを設定
spring.sql.init.mode=always

# Log表示設定
logging.level.com.example.nagahoribashi_walk.repository=DEBUG

# DBのカラム名(スネークケース)とJavaのフィールド名(キャメルケース)を自動変換する設定
mybatis.configuration.map-underscore-to-camel-case=true

# TomcatのPOSTデータサイズ制限を緩和 (デフォルト2MB -> 10MB)
server.tomcat.max-http-form-post-size=10MB

# マルチパートリクエストのサイズ制限も合わせて緩和
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#外部ファイル(画像)保存先
app.upload.dir=./uploads

#本番リリーズ時はWhitelabelエラーページを無効にする
#spring.web.error.whitelabel.enabled=false